# Generated by Django 6.0 on 2025-12-09 09:50

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('m', 'MALE'), ('f', 'FEMALE')], default='L', max_length=1)),
                ('category', models.CharField(choices=[('L', 'LARGE'), ('M', 'MEDIUM'), ('S', 'SMALL')], default='m', max_length=1)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_field)),
            ],
        ),
    ]
